spring:
  application:
    name: ferry-food
  jpa:
    database: MYSQL
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        show_sql: true
      #      javax:
      #        persistence:
      #          schema-generation.scripts.action: create
      #          schema-generation.scripts.create-target: src/main/resources/import.sql
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/zendb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 3
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    baseline-on-migrate: true
